apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: eckes
spec:
  version: 8.6.2
  nodeSets:
    - name: default
      count: 3
      config:
        xpack.ml.enabled: false
        node.store.allow_mmap: false
      podTemplate:
        spec:
          initContainers:
            - name: vm-max-map
              securityContext:
                privileged: true
              command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 1Gi
            storageClassName: nfs-storage
  http:
    service:
      spec:
        type: NodePort
