apiVersion: v1
kind: Namespace
metadata:
  name: eck-stack
---
########################################################################################################################
# Elasticsearch 集群
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: eckes
  namespace: eck-stack
spec:
  version: 7.10.0
  nodeSets:
    - name: default
      count: 1
      config:
        xpack.ml.enabled: true
        node.store.allow_mmap: false
      podTemplate:
        spec:
          initContainers:
            - name: vm-max-map
              securityContext:
                privileged: true
              command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 1Gi
            storageClassName: nfs-storage
  http:
    service:
      spec:
        ports:
          - port: 9200
            targetPort: 9200
            nodePort: 31920
            name: http
          - port: 9300
            targetPort: 9300
            nodePort: 31930
            name: inner
        type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
---
########################################################################################################################
# Kibana 集群
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eckkb
  namespace: eck-stack
spec:
  version: 7.10.0
  count: 1
  elasticsearchRef:
    name: eckes
  config:
    monitoring.ui.container.elasticsearch.enabled: true
  http:
    service:
      spec:
        ports:
          - port: 5601
            targetPort: 5601
            nodePort: 31561
            name: http
        type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
---
########################################################################################################################
# Filebeat
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: eckfb
  namespace: eck-stack
spec:
  type: filebeat
  version: 7.10.0
  elasticsearchRef:
    name: eckes
  kibanaRef:
    name: eckkb
  config:
    filebeat:
      autodiscover:
        providers:
          - type: kubernetes
            node: ${NODE_NAME}
            hints:
              enabled: true
              default_config:
                type: container
                paths:
                  - /var/log/containers/*${data.kubernetes.container.id}.log
    processors:
      - add_cloud_metadata: {}
      - add_host_metadata: {}
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        containers:
          - name: filebeat
            securityContext:
              runAsUser: 0
              privileged: true
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: eck-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: eck-stack
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---