apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: eckes
spec:
  version: 8.6.2
  nodeSets:
    - name: default
      count: 3
      config:
        xpack.ml.enabled: false
        node.store.allow_mmap: false
      podTemplate:
        spec:
          initContainers:
            - name: vm-max-map
              securityContext:
                privileged: true
              command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 1Gi
            storageClassName: nfs-storage
  http:
    service:
      spec:
        ports:
          - port: 9200
            targetPort: 9200
            nodePort: 31920
            name: outer
          - port: 9300
            targetPort: 9300
            nodePort: 31930
            name: inner
        type: NodePort
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eckkb
spec:
  version: 8.6.2
  count: 2
  elasticsearchRef:
    name: eckes
  http:
    service:
      spec:
        ports:
          - port: 5601
            targetPort: 5601
            nodePort: 31561
        type: NodePort