apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-conf
  namespace: eck-stack
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: [ "http://eckes-es-http:9200" ]
    xpack.monitoring.elasticsearch.username: "elastic"
    xpack.monitoring.elasticsearch.password: "376d4Gd902sfc0bEj41yFJYr"
  pipelines.yml: |
    - pipeline.id: main
      path.config: "/usr/share/logstash/pipeline/main.conf"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: eck-stack
data:
  main.conf: |
    input {
        tcp {
          port => "5144"
          codec => "json"
          type => "rsyslog"
        }
    }
    filter {
        if [level] =~ /info/ {
          mutate {
            add_field => {"source" => "info"}
          }
        } else {
          mutate {
            add_field => {"source" => "default"}
          }
        }
    }
    output {
      elasticsearch {
        index => "%{source}-log-%{+YYY.MM.dd}"
        hosts => ["http://eckes-es-http:9200"]
        user => "elastic"
        password => "376d4Gd902sfc0bEj41yFJYr"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eckls
  namespace: eck-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eckls
  template:
    metadata:
      namespace: eck-stack
      labels:
        app: eckls
    spec:
      containers:
        - name: logstash
          image: logstash:8.6.2
          env:
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eckes-es-elastic-user
                  key: elastic
          ports:
            - containerPort: 5144
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/usr/share/logstash/config/logstash.yml"
              subPath: "logstash.yml"
            - name: config
              mountPath: "/usr/share/logstash/config/pipelines.conf"
              subPath: "pipelines.conf"
            - name: pip-conf
              mountPath: "/usr/share/logstash/pipeline/main.conf"
              subPath: "main.conf"
      volumes:
        - name: config
          configMap:
            name: logstash-conf
        - name: pip-conf
          configMap:
            name: pipeline-config
---
apiVersion: v1
kind: Service
metadata:
  name: eckls-svc
  namespace: eck-stack
spec:
  selector:
    app: eckls
  ports:
    - port: 5144
      targetPort: 5144
      nodePort: 31544
  type: NodePort